server:
  port: 8088

spring:
  datasource:
    name: urpm
    url: jdbc:mysql://47.111.233.76:3306/urpm?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=CTT
    username: root
    password: 123456
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.springboot.servie.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true

  redis:
    host: 47.111.233.76
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 50
        max-idle: 8
        min-idle: 0
        max-wait: 10000

  # 404交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  # 404交给异常处理器处理
  resources:
    add-mappings: false

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.example.urpm.model.entity
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE

pagehelper:
  params: count=countSql
  # 指定分页插件使用哪种方言
  helper-dialect: mysql
  # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
  reasonable: true
  support-methods-arguments: 'true'

mapper:
  not-empty: false
  identity: MYSQL

# Logger Config
logging:
  level:
    com.example.urpm: debug

properties:
  encryptAESKey: VVJQTS1KV1RLZXktZGluZ2ppbnlhbmc=
  encryptJWTKey: ZGluZ2ppbnlhbmctVVJQTS1KV1RLZXk=
  accessTokenExpireTime: 300000
  refreshTokenExpireTime: 1800
  shiroCacheExpireTime: 300